export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
